// Generated by gencpp from file ros_service_assignment/RectangleAeraService.msg
// DO NOT EDIT!


#ifndef ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAERASERVICE_H
#define ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAERASERVICE_H

#include <ros/service_traits.h>


#include <ros_service_assignment/RectangleAeraServiceRequest.h>
#include <ros_service_assignment/RectangleAeraServiceResponse.h>


namespace ros_service_assignment
{

struct RectangleAeraService
{

typedef RectangleAeraServiceRequest Request;
typedef RectangleAeraServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RectangleAeraService
} // namespace ros_service_assignment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_service_assignment::RectangleAeraService > {
  static const char* value()
  {
    return "92e9c8f940da77dc3e1bc289f7dd146e";
  }

  static const char* value(const ::ros_service_assignment::RectangleAeraService&) { return value(); }
};

template<>
struct DataType< ::ros_service_assignment::RectangleAeraService > {
  static const char* value()
  {
    return "ros_service_assignment/RectangleAeraService";
  }

  static const char* value(const ::ros_service_assignment::RectangleAeraService&) { return value(); }
};


// service_traits::MD5Sum< ::ros_service_assignment::RectangleAeraServiceRequest> should match
// service_traits::MD5Sum< ::ros_service_assignment::RectangleAeraService >
template<>
struct MD5Sum< ::ros_service_assignment::RectangleAeraServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_service_assignment::RectangleAeraService >::value();
  }
  static const char* value(const ::ros_service_assignment::RectangleAeraServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_service_assignment::RectangleAeraServiceRequest> should match
// service_traits::DataType< ::ros_service_assignment::RectangleAeraService >
template<>
struct DataType< ::ros_service_assignment::RectangleAeraServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_service_assignment::RectangleAeraService >::value();
  }
  static const char* value(const ::ros_service_assignment::RectangleAeraServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_service_assignment::RectangleAeraServiceResponse> should match
// service_traits::MD5Sum< ::ros_service_assignment::RectangleAeraService >
template<>
struct MD5Sum< ::ros_service_assignment::RectangleAeraServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_service_assignment::RectangleAeraService >::value();
  }
  static const char* value(const ::ros_service_assignment::RectangleAeraServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_service_assignment::RectangleAeraServiceResponse> should match
// service_traits::DataType< ::ros_service_assignment::RectangleAeraService >
template<>
struct DataType< ::ros_service_assignment::RectangleAeraServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_service_assignment::RectangleAeraService >::value();
  }
  static const char* value(const ::ros_service_assignment::RectangleAeraServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAERASERVICE_H
