// Generated by gencpp from file lab_1_pkg/CustomService.msg
// DO NOT EDIT!


#ifndef LAB_1_PKG_MESSAGE_CUSTOMSERVICE_H
#define LAB_1_PKG_MESSAGE_CUSTOMSERVICE_H

#include <ros/service_traits.h>


#include <lab_1_pkg/CustomServiceRequest.h>
#include <lab_1_pkg/CustomServiceResponse.h>


namespace lab_1_pkg
{

struct CustomService
{

typedef CustomServiceRequest Request;
typedef CustomServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomService
} // namespace lab_1_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab_1_pkg::CustomService > {
  static const char* value()
  {
    return "1de2a7958fd3947b5dd3ec41292a1bb8";
  }

  static const char* value(const ::lab_1_pkg::CustomService&) { return value(); }
};

template<>
struct DataType< ::lab_1_pkg::CustomService > {
  static const char* value()
  {
    return "lab_1_pkg/CustomService";
  }

  static const char* value(const ::lab_1_pkg::CustomService&) { return value(); }
};


// service_traits::MD5Sum< ::lab_1_pkg::CustomServiceRequest> should match
// service_traits::MD5Sum< ::lab_1_pkg::CustomService >
template<>
struct MD5Sum< ::lab_1_pkg::CustomServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab_1_pkg::CustomService >::value();
  }
  static const char* value(const ::lab_1_pkg::CustomServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab_1_pkg::CustomServiceRequest> should match
// service_traits::DataType< ::lab_1_pkg::CustomService >
template<>
struct DataType< ::lab_1_pkg::CustomServiceRequest>
{
  static const char* value()
  {
    return DataType< ::lab_1_pkg::CustomService >::value();
  }
  static const char* value(const ::lab_1_pkg::CustomServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab_1_pkg::CustomServiceResponse> should match
// service_traits::MD5Sum< ::lab_1_pkg::CustomService >
template<>
struct MD5Sum< ::lab_1_pkg::CustomServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab_1_pkg::CustomService >::value();
  }
  static const char* value(const ::lab_1_pkg::CustomServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab_1_pkg::CustomServiceResponse> should match
// service_traits::DataType< ::lab_1_pkg::CustomService >
template<>
struct DataType< ::lab_1_pkg::CustomServiceResponse>
{
  static const char* value()
  {
    return DataType< ::lab_1_pkg::CustomService >::value();
  }
  static const char* value(const ::lab_1_pkg::CustomServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB_1_PKG_MESSAGE_CUSTOMSERVICE_H
