// Generated by gencpp from file lab_1_pkg/CustomServiceRequest.msg
// DO NOT EDIT!


#ifndef LAB_1_PKG_MESSAGE_CUSTOMSERVICEREQUEST_H
#define LAB_1_PKG_MESSAGE_CUSTOMSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab_1_pkg
{
template <class ContainerAllocator>
struct CustomServiceRequest_
{
  typedef CustomServiceRequest_<ContainerAllocator> Type;

  CustomServiceRequest_()
    : arg_1(0)  {
    }
  CustomServiceRequest_(const ContainerAllocator& _alloc)
    : arg_1(0)  {
  (void)_alloc;
    }



   typedef uint32_t _arg_1_type;
  _arg_1_type arg_1;





  typedef boost::shared_ptr< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CustomServiceRequest_

typedef ::lab_1_pkg::CustomServiceRequest_<std::allocator<void> > CustomServiceRequest;

typedef boost::shared_ptr< ::lab_1_pkg::CustomServiceRequest > CustomServiceRequestPtr;
typedef boost::shared_ptr< ::lab_1_pkg::CustomServiceRequest const> CustomServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator1> & lhs, const ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.arg_1 == rhs.arg_1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator1> & lhs, const ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab_1_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6476a566acf52aa10a2c0826092b93a";
  }

  static const char* value(const ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6476a566acf52aaULL;
  static const uint64_t static_value2 = 0x10a2c0826092b93aULL;
};

template<class ContainerAllocator>
struct DataType< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab_1_pkg/CustomServiceRequest";
  }

  static const char* value(const ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# CustomService.srv\n"
"# Request fields\n"
"uint32 arg_1\n"
;
  }

  static const char* value(const ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arg_1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab_1_pkg::CustomServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "arg_1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.arg_1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB_1_PKG_MESSAGE_CUSTOMSERVICEREQUEST_H
